name: EndToggle
version: 1.1
main: de.einFux.amethystra.Main
description: Plugin für End-Steuerung & Server-Restart
author: einFux
commands:
  toggleend:
    description: Toggelt den Zugang zum End für Nicht-OPs.
    usage: /toggleend
    permission: op
  serverrestart:
    description: Startet den Server-Neustart mit Countdown.
    permission: op
  endeventstart:
    description: Startet das End-Event.
    permission: op
